const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILED: 'DELETE_USERS_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_ALL_DATASETS_SUCCESS: 'FETCH_ALL_DATASETS_SUCCESS',
    FETCH_ALL_DATASETS_FAILED: 'FETCH_ALL_DATASETS_FAILED',

    CREATE_DATASET_SUCCESS: 'CREATE_DATASET_SUCCESS',
    CREATE_DATASET_FAILED: 'CREATE_DATASET_FAILED',

    UPDATE_DATASET_SUCCESS: 'UPDATE_DATASET_SUCCESS',
    UPDATE_DATASET_FAILED: 'UPDATE_DATASET_FAILED',

    DELETE_DATASET_SUCCESS: 'DELETE_DATASET_SUCCESS',
    DELETE_DATASET_FAILED: 'DELETE_DATASET_FAILED',

    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILED: 'FETCH_CATEGORY_FAILED',

    FETCH_FORMAT_SUCCESS: 'FETCH_FORMAT_SUCCESS',
    FETCH_FORMAT_FAILED: 'FETCH_FORMAT_FAILED',

    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILED: 'FETCH_STATUS_FAILED',

    FETCH_TOP_DATAS_SUCCESS: 'FETCH_TOP_DATAS_SUCCESS',
    FETCH_TOP_DATAS_FAILED: 'FETCH_TOP_DATAS_FAILED',

})

export default actionTypes; 