const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: 'USER_REGISTER_FAIL',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    DELETE_USERS_SUCCESS: 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILED: 'DELETE_USERS_FAILED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    FETCH_ALL_DATASETS_SUCCESS: 'FETCH_ALL_DATASETS_SUCCESS',
    FETCH_ALL_DATASETS_FAILED: 'FETCH_ALL_DATASETS_FAILED',

    CREATE_DATASET_SUCCESS: 'CREATE_DATASET_SUCCESS',
    CREATE_DATASET_FAILED: 'CREATE_DATASET_FAILED',

    UPDATE_DATASET_SUCCESS: 'UPDATE_DATASET_SUCCESS',
    UPDATE_DATASET_FAILED: 'UPDATE_DATASET_FAILED',

    DELETE_DATASET_SUCCESS: 'DELETE_DATASET_SUCCESS',
    DELETE_DATASET_FAILED: 'DELETE_DATASET_FAILED',

    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILED: 'FETCH_CATEGORY_FAILED',

    FETCH_FORMAT_SUCCESS: 'FETCH_FORMAT_SUCCESS',
    FETCH_FORMAT_FAILED: 'FETCH_FORMAT_FAILED',

    FETCH_STATUS_SUCCESS: 'FETCH_STATUS_SUCCESS',
    FETCH_STATUS_FAILED: 'FETCH_STATUS_FAILED',

    FETCH_TOP_DATAS_SUCCESS: 'FETCH_TOP_DATAS_SUCCESS',
    FETCH_TOP_DATAS_FAILED: 'FETCH_TOP_DATAS_FAILED',

    FETCH_DETAIL_DATASET_START: 'FETCH_DETAIL_DATASET_START',
    FETCH_DETAIL_DATASET_SUCCESS: 'FETCH_DETAIL_DATASET_SUCCESS',
    FETCH_DETAIL_DATASET_FAILED: 'FETCH_DETAIL_DATASET_FAILED',

    // Transaction / Payment
    PURCHASE_DATASET_START: 'PURCHASE_DATASET_START',
    PURCHASE_DATASET_SUCCESS: 'PURCHASE_DATASET_SUCCESS',
    PURCHASE_DATASET_FAILED: 'PURCHASE_DATASET_FAILED',

    CHECK_PERMISSION_START: 'CHECK_PERMISSION_START',
    CHECK_PERMISSION_SUCCESS: 'CHECK_PERMISSION_SUCCESS',
    CHECK_PERMISSION_FAILED: 'CHECK_PERMISSION_FAILED',

    GET_PURCHASES_START: 'GET_PURCHASES_START',
    GET_PURCHASES_SUCCESS: 'GET_PURCHASES_SUCCESS',
    GET_PURCHASES_FAILED: 'GET_PURCHASES_FAILED',

    // THÊM MỚI cho Transaction
    CREATE_TRANSACTION_START: 'CREATE_TRANSACTION_START',
    CREATE_TRANSACTION_SUCCESS: 'CREATE_TRANSACTION_SUCCESS',
    CREATE_TRANSACTION_FAILED: 'CREATE_TRANSACTION_FAILED',

    SIMULATE_PAYMENT_START: 'SIMULATE_PAYMENT_START',
    SIMULATE_PAYMENT_SUCCESS: 'SIMULATE_PAYMENT_SUCCESS',
    SIMULATE_PAYMENT_FAILED: 'SIMULATE_PAYMENT_FAILED',

    GET_TRANSACTION_HISTORY_START: 'GET_TRANSACTION_HISTORY_START',
    GET_TRANSACTION_HISTORY_SUCCESS: 'GET_TRANSACTION_HISTORY_SUCCESS',
    GET_TRANSACTION_HISTORY_FAILED: 'GET_TRANSACTION_HISTORY_FAILED',


    GET_MY_PAYOUTS_START: 'GET_MY_PAYOUTS_START',
    GET_MY_PAYOUTS_SUCCESS: 'GET_MY_PAYOUTS_SUCCESS',
    GET_MY_PAYOUTS_FAILED: 'GET_MY_PAYOUTS_FAILED',

    GET_BALANCE_START: 'GET_BALANCE_START',
    GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
    GET_BALANCE_FAILED: 'GET_BALANCE_FAILED',

    REQUEST_WITHDRAW_START: 'REQUEST_WITHDRAW_START',
    REQUEST_WITHDRAW_SUCCESS: 'REQUEST_WITHDRAW_SUCCESS',
    REQUEST_WITHDRAW_FAILED: 'REQUEST_WITHDRAW_FAILED',

    GET_WITHDRAWAL_HISTORY_START: 'GET_WITHDRAWAL_HISTORY_START',
    GET_WITHDRAWAL_HISTORY_SUCCESS: 'GET_WITHDRAWAL_HISTORY_SUCCESS',
    GET_WITHDRAWAL_HISTORY_FAILED: 'GET_WITHDRAWAL_HISTORY_FAILED',

    GET_REVENUE_START: 'GET_REVENUE_START',
    GET_REVENUE_SUCCESS: 'GET_REVENUE_SUCCESS',
    GET_REVENUE_FAILED: 'GET_REVENUE_FAILED',

    FETCH_MARKET_ANALYTICS_START: 'FETCH_MARKET_ANALYTICS_START',
    FETCH_MARKET_ANALYTICS_SUCCESS: 'FETCH_MARKET_ANALYTICS_SUCCESS',
    FETCH_MARKET_ANALYTICS_FAILED: 'FETCH_MARKET_ANALYTICS_FAILED',

    FETCH_TOP_INTEREST_DATASETS_SUCCESS: 'FETCH_TOP_INTEREST_DATASETS_SUCCESS',
    FETCH_TOP_INTEREST_DATASETS_FAILED: 'FETCH_TOP_INTEREST_DATASETS_FAILED',

    FETCH_AI_INSIGHTS_START: 'FETCH_AI_INSIGHTS_START',
    FETCH_AI_INSIGHTS_SUCCESS: 'FETCH_AI_INSIGHTS_SUCCESS',
    FETCH_AI_INSIGHTS_FAILED: 'FETCH_AI_INSIGHTS_FAILED',
    CLEAR_AI_INSIGHTS: 'CLEAR_AI_INSIGHTS',

    // Admin Payout
    GET_PENDING_PAYOUTS_START: 'GET_PENDING_PAYOUTS_START',
    GET_PENDING_PAYOUTS_SUCCESS: 'GET_PENDING_PAYOUTS_SUCCESS',
    GET_PENDING_PAYOUTS_FAILED: 'GET_PENDING_PAYOUTS_FAILED',

    PROCESS_PAYOUT_START: 'PROCESS_PAYOUT_START',
    PROCESS_PAYOUT_SUCCESS: 'PROCESS_PAYOUT_SUCCESS',
    PROCESS_PAYOUT_FAILED: 'PROCESS_PAYOUT_FAILED',

    GET_PAYOUT_STATISTICS_START: 'GET_PAYOUT_STATISTICS_START',
    GET_PAYOUT_STATISTICS_SUCCESS: 'GET_PAYOUT_STATISTICS_SUCCESS',
    GET_PAYOUT_STATISTICS_FAILED: 'GET_PAYOUT_STATISTICS_FAILED',

    // EV Analytics
    FETCH_EV_ANALYTICS_START: 'FETCH_EV_ANALYTICS_START',
    FETCH_EV_ANALYTICS_SUCCESS: 'FETCH_EV_ANALYTICS_SUCCESS',
    FETCH_EV_ANALYTICS_ERROR: 'FETCH_EV_ANALYTICS_ERROR',
})

export default actionTypes; 