version: '3.8'
services:
  db-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ev-data-analytics-marketplace
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"